"""
FacilityMind — Pydantic Data Schemas
Defines the data structures flowing between agents in the multi-agent system.
Each agent produces typed output that serves as input for the next agent in the pipeline.
"""

from typing import Optional, List
from pydantic import BaseModel, Field


class SourceCitation(BaseModel):
    """Citation of a specific source within building blueprints."""
    plano: str = Field(..., description="Blueprint ID (e.g., E-14, P-01, A-03)")
    pagina: int = Field(..., description="Page number within the PDF")
    texto_citado: str = Field(..., description="Exact text or paragraph cited from the blueprint")
    confianza_cita: float = Field(0.0, ge=0.0, le=1.0, description="Confidence that this citation is relevant")


class PerceptionOutput(BaseModel):
    """
    Output from Agent 1 — Perception.
    Analyzes audio + image + text from the field technician to extract structured data.
    """
    piso: Optional[str] = Field(None, description="Detected floor number (e.g., '14', 'GF', 'B1')")
    torre: Optional[str] = Field(None, description="Tower or wing identifier (e.g., '2', 'A', 'North')")
    habitacion: Optional[str] = Field(None, description="Room or unit identifier (e.g., '14-B', '302')")
    objeto_detectado: Optional[str] = Field(None, description="Identified object: electrical outlet, pipe, breaker, valve, etc.")
    objetivo_consulta: str = Field(..., description="Technician's objective (inferred from the query)")
    disciplina: Optional[str] = Field(None, description="Inferred discipline: electrical, plumbing, HVAC, structural, general")
    notas_urgencia: Optional[str] = Field(None, description="Urgency or risk keywords detected")
    idioma_detectado: str = Field("en", description="Primary input language (en, es, etc.)")
    confianza_percepcion: float = Field(0.0, ge=0.0, le=1.0, description="Overall perception confidence level (0-1)")
    raw_transcripcion: Optional[str] = Field(None, description="Raw audio transcription (if applicable)")


class TracedCircuit(BaseModel):
    """Represents a circuit or line traced through building blueprints."""
    nodos: List[str] = Field(default_factory=list, description="Ordered list of components (e.g., ['Outlet R-14-B-03', 'J-Box J-14-B-01', 'Circuit C-14-07', 'Panel PP-14-EAST', 'Breaker 23'])")
    descripcion: str = Field("", description="Textual description of the traced path")
    tipo: str = Field("", description="Trace type: electrical, plumbing, HVAC, etc.")


class ReasonerOutput(BaseModel):
    """
    Output from Agent 2 — Technical Reasoner.
    Generates a candidate technical response based on RAG + Long Context.
    """
    respuesta_candidata: str = Field(..., description="Complete and detailed technical response")
    sources: List[SourceCitation] = Field(default_factory=list, description="Cited blueprint sources")
    circuito_trazado: Optional[TracedCircuit] = Field(None, description="Traced component path")
    pasos_recomendados: List[str] = Field(default_factory=list, description="Recommended action steps for the technician")
    materiales_mencionados: List[str] = Field(default_factory=list, description="Materials or specifications mentioned in the response")
    normativa_citada: Optional[str] = Field(None, description="Regulatory codes or standards cited (NEC, ISO, etc.)")
    confianza_inicial: float = Field(0.0, ge=0.0, le=1.0, description="Confidence of the candidate response")
    advertencias_tecnicas: List[str] = Field(default_factory=list, description="Technical warnings detected")


class SafetyAssessment(BaseModel):
    """Safety evaluation of the candidate response."""
    riesgo_electrico: bool = Field(False, description="Involves electrical risk")
    riesgo_plomeria: bool = Field(False, description="Involves flood or gas risk")
    afecta_emergencia: bool = Field(False, description="Affects emergency systems")
    afecta_ascensores: bool = Field(False, description="Affects elevator systems")
    afecta_alarmas: bool = Field(False, description="Affects alarm or fire protection systems")
    requiere_loto: bool = Field(False, description="Requires Lock-Out/Tag-Out (LOTO) procedure")
    nivel_riesgo: str = Field("low", description="low, medium, high, critical")
    descripcion_riesgo: Optional[str] = Field(None, description="Explanation of identified risk")


class ValidatorOutput(BaseModel):
    """
    Output from Agent 3 — Validator.
    Verifies the candidate response against original blueprints.
    """
    aprobado: bool = Field(..., description="Whether the response passed validation")
    respuesta_final: str = Field(..., description="Corrected or approved final response")
    confianza_final: float = Field(0.0, ge=0.0, le=1.0, description="Confidence after validation")
    sources_verificadas: List[SourceCitation] = Field(default_factory=list, description="Sources verified as accurate")
    advertencias: List[str] = Field(default_factory=list, description="Warnings generated by the validator")
    requiere_supervisor: bool = Field(False, description="Whether supervisor approval is required before proceeding")
    motivo_rechazo: Optional[str] = Field(None, description="Reason for rejection, if applicable")
    alucinaciones_detectadas: List[str] = Field(default_factory=list, description="Detected fabricated data")
    safety: SafetyAssessment = Field(default_factory=SafetyAssessment, description="Safety assessment results")


class VisualizationOutput(BaseModel):
    """
    Output from Agent 4 — Visualizer.
    Generates images and diagrams to illustrate the response.
    """
    imagen_generada: Optional[str] = Field(None, description="Path or URL of the generated image (traced circuit)")
    imagen_descripcion: Optional[str] = Field(None, description="Description of the visualization content")
    diagrama_mermaid: Optional[str] = Field(None, description="Mermaid diagram for UI rendering")
    resumen_visual: str = Field("", description="Visual summary of the response for the technician")
    mapa_calor: Optional[str] = Field(None, description="Path to building heatmap (if applicable)")


class FacilityMindResponse(BaseModel):
    """Complete final response from the orchestrated system."""
    respuesta: str = Field(..., description="Response text for the technician")
    sources: List[SourceCitation] = Field(default_factory=list, description="Verified sources")
    circuito_trazado: Optional[TracedCircuit] = Field(None, description="Traced circuit path, if applicable")
    confianza: float = Field(0.0, ge=0.0, le=1.0, description="Final system confidence")
    advertencias: List[str] = Field(default_factory=list, description="All accumulated warnings")
    requiere_supervisor: bool = Field(False, description="Whether supervisor review is required")
    visualizacion: Optional[VisualizationOutput] = Field(None, description="Generated visualizations")
    safety: SafetyAssessment = Field(default_factory=SafetyAssessment, description="Safety assessment results")
    debug: dict = Field(default_factory=dict, description="Debug information from each agent")
    tiempo_procesamiento_ms: int = Field(0, description="Total processing time in milliseconds")


class PlanoMetadata(BaseModel):
    """Metadata for an ingested blueprint."""
    plano_id: str = Field(..., description="Unique blueprint ID (e.g., E-14, P-01)")
    tipo_plano: str = Field(..., description="electrical, plumbing, architectural, structural, general")
    edificio: str = Field("", description="Building Identifier")
    piso: Optional[str] = Field(None, description="Floor covered by the blueprint")
    torre: Optional[str] = Field(None, description="Tower or wing covered by the blueprint")
    total_paginas: int = Field(0, description="Total number of pages")
    fecha_ingesta: Optional[str] = None
    descripcion: Optional[str] = Field(None, description="Blueprint description")


class ChatMessage(BaseModel):
    """Chat message for conversational interaction."""
    role: str = Field(..., description="user or assistant")
    content: str = Field(..., description="Message content")
    timestamp: Optional[str] = None
    tiene_imagen: bool = Field(False)
    tiene_audio: bool = Field(False)
